#！！！本地免流版！！！
proxies:
#此处用来放本地免流配置，本地免流只能免80/443端口的TCP，其他连接（包括所有udp）不行
  - name: "百度免流"
    type: http
    server: 157.0.148.53
    port: 443
    headers:
      X-T5-Auth: "1962898709"
      User-Agent:
        "okhttp/3.11.0 Dalvik/2.1.0 (Linux; U; Android 11; Redmi K30 5G Build/RKQ1.200826.002)
        baiduboxapp/11.0.5.12 (Baidu; P1 11)"

proxy-providers:
  
  可乐云:
    type: http
    url: "https://www.naiun.co/api/v1/client/subscribe?token=bb71ad25fd1d7341560483c7b78a61a7"
    path: ./proxy_providers/可乐云.yaml
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800
  魔戒:
    type: http
    url: "订阅链接地址"
    path: ./proxy_providers/魔戒.yaml
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800
  备用:
    type: http
    url: "在底下选一个吧，如果有好的欢迎提交"
    path: ./proxy_providers/备用.yaml
    interval: 10800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800
#欢迎提交更多白嫖订阅
#https://pastebin.com/raw/GxR5pELe
#https://openit.daycat.space/clash
#https://nullnode.top/clash主站 下属 https://nullnode.top/clashnode
#可以白嫖的机场 https://acec.cloud/
# 魔戒 可乐云 为机场名，可以更换，要换必须全换，建议使用编辑器的查找功能避免遗漏
proxy-groups:
  - name: 机场
    type: select
    proxies:
      - 可乐云
      - 魔戒
      - 备用
      - 美国节点
      - 负载均衡

  - name: 可乐云
    type: select
    use:
      - 可乐云

  - name: 魔戒
    type: select
    use:
      - 魔戒

  - name: 备用
    type: select
    use:
      - 备用

    
  - name: 美国节点
    type: select
    use:
      - 可乐云
      - 魔戒
      - 备用
    filter: '美国|USA|美國'

  - name: 负载均衡
    type: load-balance
    use:
      - 可乐云
    url: 'http://www.gstatic.com/generate_204'
    interval: 1800
    filter: '美国|USA|美國.*1.0'
    strategy: consistent-hashing
#meta的特性，如果你经常使用某个地区节点可以使用过滤器便于选择 美国节点 可以改为其他名称
#但是要改就得全改 ，建议使用文本编辑器的替换功能避免遗漏；过滤器内容用 | 分割，支持通配符
#可乐云性增加了负载均衡节点
  - name: 墙内网址
    type: select
    proxies:
      - DIRECT
      - 机场

  - name: 墙内可免
    type: select
    proxies:
      - 墙内网址
      - 本地免流

  - name: 本地免流
    type: select
    proxies:
      - 百度免流


  - name: 其他
    type: select
    proxies:
      - DIRECT
      - 机场
      - 墙内网址

rule-providers:
  userDirect:
    type: file
    behavior: classical
    path: ./rule_providers/userDirect.yaml
    #用户自定义直连，文件在data/clash/rule-provider/userdirect，需要的自己写入，格式参照备用里面的clash官方文档
rules:
  - RULE-SET,userDirect,DIRECT
  - GEOSITE,category-ads-all,REJECT
  - GEOIP,private,DIRECT
#-------免流相关规则
  #此处应有把微信qq支付宝等事逼不走免流的规则，让我看看geo教程
  - AND,((NETWORK,TCP),(GEOSITE,geolocation-cn),(DST-PORT,80/443)),墙内可免
  - AND,((NETWORK,UDP),(GEOSITE,geolocation-cn)),墙内网址
  - GEOSITE,geolocation-cn,墙内网址

  - AND,((NETWORK,TCP),(GEOIP,CN,no-resolve),(DST-PORT,80/443)),墙内可免
  - AND,((NETWORK,UDP),(GEOIP,CN,no-resolve)),墙内网址
  - GEOIP,CN,墙内网址
#-----------------墙外流量
  - GEOSITE,geolocation-!cn,机场
  - GEOIP,!CN,机场
  - MATCH,其他
